# Generated by Django 5.0.3 on 2024-03-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
