# Generated by Django 5.0.3 on 2024-03-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappy_app', '0002_alter_customers_photo_alter_employees_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
