# Generated by Django 5.0.3 on 2024-03-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappy_app', '0003_alter_customers_photo_alter_employees_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
