# Generated by Django 5.0.3 on 2024-03-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lappy_app', '0004_alter_products_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_email', models.EmailField(max_length=200)),
            ],
        ),
    ]
